<<<<<<< HEAD
# Generated by Django 5.1.1 on 2026-03-19 20:22

=======
# Generated by Django 6.0.3 on 2026-04-07 14:18

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
>>>>>>> c7fbb98 (DuySang01: Hoàn thiện chức năng Bác sĩ và Lịch làm việc)
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> c7fbb98 (DuySang01: Hoàn thiện chức năng Bác sĩ và Lịch làm việc)
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Anh', 'Anh'), ('Chị', 'Chị')], max_length=10)),
                ('fullname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
=======
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Họ tên')),
                ('title', models.CharField(blank=True, max_length=80, verbose_name='Chức vụ')),
                ('qualification', models.CharField(blank=True, max_length=120, verbose_name='Trình độ')),
                ('specialty', models.CharField(blank=True, max_length=120, verbose_name='Chuyên khoa')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='Số năm kinh nghiệm')),
                ('bio', models.TextField(blank=True, verbose_name='Tiểu sử')),
                ('avatar', models.CharField(blank=True, max_length=255, verbose_name='Link ảnh đại diện')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('doctor', 'Doctor'), ('admin', 'Admin')], default='customer', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d{9,12}$', 'Số điện thoại chỉ chứa chữ số (9-12 chữ số).')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Thứ Hai'), (1, 'Thứ Ba'), (2, 'Thứ Tư'), (3, 'Thứ Năm'), (4, 'Thứ Sáu'), (5, 'Thứ Bảy'), (6, 'Chủ Nhật')], verbose_name='Ngày trực')),
                ('shift', models.CharField(choices=[('morning', 'Ca sáng'), ('afternoon', 'Ca chiều')], max_length=10, verbose_name='Ca trực')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='appointments.doctor')),
            ],
            options={
                'verbose_name': 'Lịch làm việc',
                'verbose_name_plural': 'Lịch làm việc',
                'unique_together': {('doctor', 'weekday', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{9,12}$', 'Số điện thoại chỉ chứa chữ số (9-12 chữ số).')])),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('shift', models.CharField(choices=[('morning', 'Ca sáng'), ('afternoon', 'Ca chiều')], max_length=10)),
                ('symptom', models.TextField(blank=True)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.doctor')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.service')),
            ],
            options={
                'ordering': ['-date', 'shift'],
                'indexes': [models.Index(fields=['date', 'shift'], name='appointment_date_f75a70_idx')],
            },
>>>>>>> c7fbb98 (DuySang01: Hoàn thiện chức năng Bác sĩ và Lịch làm việc)
        ),
    ]
