# Generated by Django 5.1.1 on 2026-03-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Lịch hẹn', 'verbose_name_plural': 'Danh sách lịch hẹn'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày hẹn dự kiến'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='branch',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chi nhánh'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dịch vụ quan tâm'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm đặt'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='fullname',
            field=models.CharField(max_length=255, verbose_name='Họ tên'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='gender',
            field=models.CharField(choices=[('Anh', 'Anh'), ('Chị', 'Chị')], max_length=10, verbose_name='Danh xưng'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Mong muốn khách hàng'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Số điện thoại'),
        ),
    ]
