# Generated by Django 5.1.1 on 2026-03-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specialty', models.CharField(max_length=200, verbose_name='Chuyên khoa')),
                ('experience', models.TextField(verbose_name='Kinh nghiệm')),
                ('image_url', models.URLField(max_length=500, verbose_name='Link ảnh bác sĩ')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('image_url', models.URLField(max_length=500, verbose_name='Link ảnh minh họa')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200, verbose_name='Tên dịch vụ')),
                ('unit', models.CharField(max_length=50, verbose_name='Đơn vị')),
                ('price', models.IntegerField(verbose_name='Giá tiền')),
            ],
            options={
                'verbose_name': 'Bảng giá',
                'verbose_name_plural': 'Quản lý bảng giá',
            },
        ),
    ]
