# Generated by Django 6.0.3 on 2026-04-07 20:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_add_user_to_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
        migrations.AddField(
            model_name='doctor',
            name='details',
            field=models.TextField(blank=True, verbose_name='Chi tiết'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='highlights',
            field=models.TextField(blank=True, help_text='Nhập mỗi điểm mạnh trên một dòng', verbose_name='Điểm mạnh'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{9,12}$', 'Số điện thoại chỉ chứa chữ số (9-12 chữ số).')], verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.TextField(verbose_name='Mô tả ngắn'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Link ảnh bác sĩ'),
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Thứ 2', 'Thứ 2'), ('Thứ 3', 'Thứ 3'), ('Thứ 4', 'Thứ 4'), ('Thứ 5', 'Thứ 5'), ('Thứ 6', 'Thứ 6'), ('Thứ 7', 'Thứ 7'), ('Chủ nhật', 'Chủ nhật')], max_length=20, verbose_name='Ngày trong tuần')),
                ('start_time', models.TimeField(verbose_name='Bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Kết thúc')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chú')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='appointments.doctor')),
            ],
            options={
                'verbose_name': 'Lịch làm việc',
                'verbose_name_plural': 'Lịch làm việc',
                'ordering': ['doctor', 'day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('doctor', 'Doctor'), ('admin', 'Admin')], default='customer', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d{9,12}$', 'Số điện thoại chỉ chứa chữ số (9-12 chữ số).')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
