# Generated by Django 6.0.4 on 2026-04-15 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Tên dịch vụ')),
                ('slug', models.SlugField(unique=True, verbose_name='Đường dẫn')),
                ('short_description', models.CharField(max_length=255, verbose_name='Mô tả ngắn')),
                ('process', models.TextField(verbose_name='Quy trình')),
                ('benefits', models.TextField(verbose_name='Lợi ích')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiển thị')),
            ],
            options={
                'verbose_name': 'Dịch vụ',
                'verbose_name_plural': 'Dịch vụ',
            },
        ),
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150, verbose_name='Hạng mục')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá')),
                ('unit', models.CharField(blank=True, help_text='Ví dụ: /chiếc', max_length=50, verbose_name='Đơn vị')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_items', to='catalog.service', verbose_name='Dịch vụ')),
            ],
            options={
                'verbose_name': 'Bảng giá',
                'verbose_name_plural': 'Bảng giá',
            },
        ),
        
    ]
