# Generated by Django 5.2.12 on 2026-04-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Gói sản phẩm', 'verbose_name_plural': 'Gói sản phẩm'},
        ),
    ]
