# Generated by Django 6.0.4 on 2026-04-15 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Họ và tên')),
                ('age', models.PositiveIntegerField(default=30, verbose_name='Tuổi')),
                ('years_of_experience', models.PositiveIntegerField(default=1, verbose_name='Số năm kinh nghiệm')),
                ('qualification', models.CharField(max_length=255, verbose_name='Trình độ')),
                ('achievement', models.TextField(blank=True, verbose_name='Thành tựu')),
                ('position', models.CharField(max_length=120, verbose_name='Chức vụ')),
                ('bio', models.TextField(blank=True, verbose_name='Giới thiệu')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='Ảnh đại diện')),
                ('services', models.ManyToManyField(blank=True, related_name='doctors', to='catalog.service', verbose_name='Dịch vụ phụ trách')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Bác sĩ',
                'verbose_name_plural': 'Bác sĩ',
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Thứ 2'), (1, 'Thứ 3'), (2, 'Thứ 4'), (3, 'Thứ 5'), (4, 'Thứ 6'), (5, 'Thứ 7'), (6, 'Chủ nhật')], verbose_name='Thứ')),
                ('shift', models.CharField(choices=[('morning', 'Ca sáng'), ('afternoon', 'Ca chiều')], max_length=20, verbose_name='Ca làm việc')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctors.doctor', verbose_name='Bác sĩ')),
            ],
            options={
                'verbose_name': 'Lịch làm việc bác sĩ',
                'verbose_name_plural': 'Lịch làm việc bác sĩ',
                'ordering': ['weekday', 'shift'],
                'unique_together': {('doctor', 'weekday', 'shift')},
            },
        ),
    ]
