# Generated by Django 6.0.4 on 2026-04-15 08:50

import common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Họ và tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, validators=[common.validators.validate_vietnam_phone], verbose_name='Số điện thoại')),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], default='other', max_length=10, verbose_name='Giới tính')),
                ('symptom', models.TextField(blank=True, verbose_name='Triệu chứng')),
                ('appointment_date', models.DateField(verbose_name='Ngày khám')),
                ('shift', models.CharField(choices=[('morning', 'Ca sáng'), ('afternoon', 'Ca chiều')], max_length=20, verbose_name='Buổi khám')),
                ('status', models.CharField(choices=[('pending_email', 'Chờ xác nhận email'), ('pending_payment', 'Chờ thanh toán'), ('confirmed', 'Đã xác nhận'), ('completed', 'Đã khám'), ('cancelled', 'Đã hủy'), ('no_show', 'Không đến khám')], default='pending_email', max_length=30, verbose_name='Trạng thái lịch hẹn')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('paid', 'Đã thanh toán'), ('failed', 'Thanh toán thất bại'), ('cancelled', 'Đã hủy thanh toán')], default='unpaid', max_length=20, verbose_name='Trạng thái thanh toán')),
                ('deposit_amount', models.DecimalField(decimal_places=0, default=100000, max_digits=12, verbose_name='Tiền cọc')),
                ('email_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='doctors.doctor', verbose_name='Bác sĩ')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='catalog.service', verbose_name='Dịch vụ')),
            ],
            options={
                'verbose_name': 'Lịch hẹn',
                'verbose_name_plural': 'Lịch hẹn',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Mã giao dịch')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền')),
                ('status', models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('paid', 'Đã thanh toán'), ('failed', 'Thanh toán thất bại'), ('cancelled', 'Đã hủy thanh toán')], default='unpaid', max_length=20, verbose_name='Trạng thái')),
                ('method', models.CharField(default='fake_gateway', max_length=50, verbose_name='Phương thức')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Thanh toán lúc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='appointments.appointment', verbose_name='Lịch hẹn')),
            ],
            options={
                'verbose_name': 'Giao dịch thanh toán',
                'verbose_name_plural': 'Giao dịch thanh toán',
            },
        ),
    ]
